language: cpp

dist: xenial 

sudo: required

compiler:
  - gcc

branches:
  only:
  - master
  - /^stable-\d+\.\d+/
  - /^v\d+\.\d+\.\d+$/

services:
  - docker

matrix:
  include:
    - env: TEST_SUITE=lint

    - env: TEST_SUITE=doc
      addons:
        apt:
          packages:
            - doxygen
            - expect
            - graphviz
            - python3-pip

    - env: TEST_SUITE=quick 

    - env: TEST_SUITE=external-fmt
      addons:
        apt:
          packages:
            - pkg-config

    - env: TEST_SUITE=distcheck

    - env: TEST_SUITE=hpcombi

    - env: TEST_SUITE=debug

    - env: TEST_SUITE=valgrind
      addons:
        apt:
          packages:
            - expect
            - libc6-dbg
            - libtool-bin

    - env: TEST_SUITE=quick MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-5.0

    - os: osx
      compiler: clang
      env: TEST_SUITE=quick
      osx_image: xcode8

    - env: TEST_SUITE=gap

    - env: TEST_SUITE=coverage
      addons:
        apt:
          packages:
            - lcov

    # The next suite produces a too long log file, and so terminates.
    # - env: TEST_SUITE=compile-warnings
     
    # The next test suite does not work
    # - os: osx
    #   compiler: gcc
    #   osx_image: xcode8
    #   env: TEST_SUITE=quick 
    #     - CC=gcc-5 
    #     - CXX=g++-5
    #     - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/miniconda3/lib
    #     - CFLAGS="$CFLAGS -I$HOME/miniconda3/include -O2 -g"
    #     - LDFLAGS="$LDFLAGS -L$HOME/miniconda3/lib"
before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:dns/gnu -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --only-upgrade autoconf; fi
    - if [[ "$TEST_SUITE" == "external-fmt" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b;
        export PATH=/home/travis/miniconda3/bin:$PATH;
        export PKG_CONFIG_PATH=/home/travis/miniconda3/lib/pkgconfig
        conda update --yes conda;
        conda install -c conda-forge --yes fmt;

      fi;
script:
  - ci/travis-$TEST_SUITE.sh
