# set clone depth
clone_depth: 5                  # clone entire repository history if not defined

environment:
  matrix:
    - CYG_ARCH: x86
      CYG_ROOT: C:/cygwin
    - CYG_ARCH: x86_64
      CYG_ROOT: C:/cygwin64

install:
  - '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l %CYG_ROOT%/var/cache/setup -P autoconf -P automake -P bison -P libgmp-devel -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl'

build: off

test_script:
  - '%CYG_ROOT%/bin/bash -lc "g++ --version && cd $APPVEYOR_BUILD_FOLDER && ./autogen.sh && ./configure && make check"'
